### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by springmeyer** [osmcode/osm-testdata#9]
v1.0.0 was published a while back: https://www.npmjs.com/package/osm-testdata. I see recent additions: any reason we should not publish a new version now? Should we call it v1.1.0 or v1.0.1?

/cc @joto @rclark

**Comment by joto** [comment]
Releasing a new version sounds fine. v1.1.0 is probably right, because some tests were added and there are some other light changes.
@springmeyer Can you release and/or add documentation about release process to README?

**Comment by joto** [comment]
stale

**Comment by springmeyer** [comment]
👍  to not worrying about publishing this to npm

@joto as far as the existing package up there I see that only you are an owner:

```
$ npm owner ls osm-testdata
joto <jochen@topf.org>
```

So, perhaps you want to deprecate the package to help discourage usage? https://docs.npmjs.com/cli/v6/commands/npm-deprecate
